### ISSUE TITLE
Create wheels?

### ISSUE THREAD

**Issue by endrebak** [deeptools/pyBigWig#82]
From the pybigwig main folder (where setup.py is), I have successfully created wheels for pybigwig with:

```
docker pull quay.io/pypa/manylinux1_x86_64
# or docker pull quay.io/pypa/manylinux1_i686
docker run -it -v (pwd):/io quay.io/pypa/manylinux1_x86_64
```

and then inside docker: 

```
yum install zlib-devel
yum install curl-devel

for PYBIN in /opt/python/*3[5-7]*/bin; do
    "${PYBIN}/pip" install cython  # install these requirements first
    # "${PYBIN}/pip" install -r /io/requirements.txt
    "${PYBIN}/pip" wheel /io/ -w wheelhouse/
done

for whl in wheelhouse/*.whl; do
    auditwheel repair "$whl" -w /io/wheelhouse/
done
```

Wheels are in the wheelhouse directory. Would you consider creating wheels and uploading to PyPI?

**Comment by dpryan79** [comment]
I'm not sure how well that will work since it needs to optionally link against numpy's library and not all versions of libcurl are likely to be ABI compatible. I'd suggest people use conda rather than pip, since the former is more likely to work properly.

Anyway, I'll look into whether I can upload multiple wheels depending on whether numpy is installed.

**Comment by endrebak** [comment]
Not for my sake, it might not be worth the hassle. It sounds more
complicated than I thought :)
